package:
  name: fahmunge-dev
  version: 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0
  entry_points:
    - munge-fah-data = fahmunge.cli:main

requirements:
  build:
    - setuptools
    - python
    - numpy
    - pandas
    - pytables
    - natsort
    - mdtraj 1.5.1 # TODO remove me when segment_id bug is fixed (this is installed through openmoltools)

  run:
    - python
    - numpy
    - pandas
    - pytables
    - natsort
    - mdtraj 1.5.1 # TODO remove me when segment_id bug is fixed (this is installed through openmoltools)

test:
  requires:
    - nose
    - nose-timer
    - fahmunge-dev
  imports:
    - fahmunge
  commands:
    - nosetests fahmunge --nocapture --verbosity=2 --with-doctest --with-timer
    - munge-fah-data --help
    - munge-fah-data --version
    # Test on some data
    - git clone https://github.com/choderalab/fahmunge-testdata.git
    - cd fahmunge-testdata
    - munge-fah-data --projects projects.csv --outpath munged --maxits 1 --debug
    # TODO: Test to make sure expected output is found
    - ls -ltr munged/all-atoms/10507
    - ls -ltr munged/no-solvent/10507
    # Test additional processing runs (shouldn't actually do anything)
    - munge-fah-data --projects projects.csv --outpath munged --maxits 1 --debug
    - munge-fah-data --projects projects.csv --outpath munged --maxits 2 --sleeptime 1 --debug
    # Test running with time limit for processing
    - rm -rf munged
    - munge-fah-data --projects projects.csv --outpath munged --maxits 2 --time 10 --sleeptime 0 --debug
    # Test parallel
    - rm -rf munged
    - munge-fah-data --projects projects.csv --outpath munged --maxits 1 --nprocesses 2 --debug
    # Corrupt a file
    - rm -f munged/no-solvent/11507/run1-clone1.h5; touch munged/no-solvent/11507/run1-clone1.h5
    - munge-fah-data --projects projects.csv --outpath munged --maxits 1 --debug

about:
  home: https://github.com/choderalab/fahmunge
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
