package:
  name: fahmunge-dev
  version: 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - setuptools
    - python
    - numpy
    - mdtraj-dev

  run:
    - python
    - numpy
    - mdtraj-dev

test:
  requires:
    - nose
    - nose-timer
    - fahmunge-dev
  imports:
    - fahmunge
  tests:
    - nosetests fahmunge --nocapture --verbosity=2 --with-doctest --with-timer
    # TODO: Test command-line stuff

about:
  home: https://github.com/choderalab/fahmunge
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
