package:
  name: fahmunge-dev
  version: 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0
  entry_points:
    - munge-fah-data = fahmunge.cli:main

requirements:
  build:
    - setuptools
    - python
    - numpy
    - pandas
    - pytables
    - natsort
    - mdtraj 1.5.1 # TODO remove me when segment_id bug is fixed (this is installed through openmoltools)

  run:
    - python
    - numpy
    - pandas
    - pytables
    - natsort
    - mdtraj 1.5.1 # TODO remove me when segment_id bug is fixed (this is installed through openmoltools)

test:
  requires:
    - nose
    - nose-timer
    - fahmunge-dev
  imports:
    - fahmunge
  commands:
    - nosetests fahmunge --nocapture --verbosity=2 --with-doctest --with-timer
    - munge-fah-data --help
    # Test on some data
    - git clone https://github.com/choderalab/fahmunge-testdata.git
    - munge-fah-data --projects fahmunge-testdata/projects.csv --outpath munged --maxits 1
    # TODO: Test to make sure expected output is found
    - ls -ltr munged

about:
  home: https://github.com/choderalab/fahmunge
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
